version: 2

sources:
  - name: custom_conversions
    schema: "{{ var('stg_custom_conversions_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: last_updated_at_ts

    tables:
      - name: conversion_orders
      - name: conversion_customers
