version: 2

sources:
  - name: fivetran_shopify
    schema: "{{ var('stg_shopify_ecommerce_fivetran_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _fivetran_synced

    tables:
      - name: customer_tag
      - name: order_tag
