version: 2

sources:
  - name: stitch_intercom_messaging
    schema: "{{ var('stg_intercom_messaging_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: email_events
      - name: campaigns
